version: '3.8'

services:
  jupiter-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: jupiter-ag-mcp:latest
    container_name: jupiter-mcp-server
    restart: unless-stopped

    # Environment variables
    environment:
      - RUST_LOG=info
      - SOLANA_NETWORK=devnet
      - SOLANA_RPC_URL=https://api.devnet.solana.com
      # Note: You should provide SOLANA_PRIVATE_KEY through secrets or .env file
      # - SOLANA_PRIVATE_KEY=${SOLANA_PRIVATE_KEY}

      # Mount environment file (create this file with your private key)
    env_file:
      - .env

    # Optional: If you need to expose ports for HTTP/WebSocket instead of stdio
    # ports:
    #   - "8080:8080"

    # Optional: Mount volumes for logs or data persistence
    # volumes:
    #   - ./logs:/app/logs

    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

    # Health check
    healthcheck:
      test: [ "CMD", "test", "-x", "./jup-mcp" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Security options
    security_opt:
      - no-new-privileges:true

    # Read-only root filesystem for security
    read_only: true

    # Temporary filesystems for writable directories
    tmpfs:
      - /tmp
      - /var/tmp
  # Optional: Add a monitoring/logging service
  # watchtower:
  #   image: containrrr/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 30 jupiter-mcp-server
